# Generated by Django 4.1.7 on 2023-03-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModelApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingdate', models.FloatField()),
                ('loc', models.CharField(max_length=30)),
                ('offerdsal', models.IntegerField()),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
    ]
